package zov.crickclient.util.player.combat.zenith.model;

public class ZenithRotationModel {
    public int rotationModelValue;
    public int rotationModelValueSecondary;
    public int rotationModelValueTertiary;
    public int rotationModelValueAlternate;
    public int rotationModelValuePrevious;
    public int rotationModelValueCurrent;
    public int rotationModelValueNext;
    public boolean rotationModelEnabled;
    public boolean rotationModelEnabledSecondary;
    public String rotationModelText;
    public long[] rotationModelTimestampArray;
    public DenseLayer rotationModelDenseLayer;
    public NormalizationLayer rotationModelNormalizationLayer;
    public OutputLayer[] rotationModelOutputLayerArray;
    public float[][] rotationModelAmountArray;
    public float[] rotationModelAmountArraySecondary;
    public float[][] rotationModelAmountArrayTertiary;
    public float[] rotationModelAmountArrayAlternate;
    public float[][] rotationModelAmountArrayPrevious;
    public float[] rotationModelAmountArrayCurrent;
    public float[][] rotationModelAmountArrayNext;
    public float[] rotationModelAmountArrayMinimum;
    public float[][] rotationModelAmountArrayMaximum;
    public float[] rotationModelAmountArrayStart;
    public boolean rotationModelEnabledTertiary;
    public float[][] rotationModelAmountArrayEnd;
    public float[] rotationModelAmountArrayVariantA;
    public float[][] rotationModelAmountArrayVariantB;
    public float[] rotationModelAmountArrayVariantC;
    public float[][] rotationModelAmountArrayVariantD;
    public float[] rotationModelAmountArrayVariantE;
    public float[][] rotationModelAmountArrayVariantF;
    public float[] rotationModelAmountArrayVariantG;
    public float[][] rotationModelAmountArrayVariantH;
    public float[] rotationModelAmountArrayVariantI;
    public float[][] rotationModelAmountArrayVariantJ;
    public float[] rotationModelAmountArrayVariantK;
}
